# Generated by Django 2.0.4 on 2018-05-29 16:33

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocket',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_key', models.CharField(editable=False, max_length=40, unique=True)),
                ('connection_key', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('open_connection', models.BooleanField(default=False)),
                ('open_sending', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
